load franke
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Aug-2020 13:16:34


%% Fit: 'untitled fit 1'.

% Set up fittype and options.
%ft = fittype( 'poly11' );
ft = fittype({'x','y'},'coefficients',{'ax','ay'})

% Fit model to data.
[fitresult, gof] = fit( [x, y], z, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [x, y], z );
legend( h, 'untitled fit 1', 'z vs. x, y', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
zlabel z
grid on
view( -39.1, -9.2 );


