# Form implementation generated from reading ui file 'forum.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Forum(object):
    def setupUi(self, Forum):
        Forum.setObjectName("Forum")
        Forum.resize(1000, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Forum.sizePolicy().hasHeightForWidth())
        Forum.setSizePolicy(sizePolicy)
        Forum.setAutoFillBackground(False)
        self.Post_pushButton = QtWidgets.QPushButton(parent=Forum)
        self.Post_pushButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.Post_pushButton.setObjectName("Post_pushButton")
        self.Delete_pushButton = QtWidgets.QPushButton(parent=Forum)
        self.Delete_pushButton.setGeometry(QtCore.QRect(110, 10, 91, 31))
        self.Delete_pushButton.setObjectName("Delete_pushButton")
        self.splitter = QtWidgets.QSplitter(parent=Forum)
        self.splitter.setGeometry(QtCore.QRect(10, 49, 971, 691))
        self.splitter.setMinimumSize(QtCore.QSize(100, 680))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Article_listWidget = QtWidgets.QListWidget(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Article_listWidget.sizePolicy().hasHeightForWidth())
        self.Article_listWidget.setSizePolicy(sizePolicy)
        self.Article_listWidget.setObjectName("Article_listWidget")
        self.widget = QtWidgets.QWidget(parent=self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header_textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header_textBrowser.sizePolicy().hasHeightForWidth())
        self.Header_textBrowser.setSizePolicy(sizePolicy)
        self.Header_textBrowser.setMinimumSize(QtCore.QSize(0, 140))
        self.Header_textBrowser.setMaximumSize(QtCore.QSize(16777215, 140))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.Header_textBrowser.setPalette(palette)
        self.Header_textBrowser.setObjectName("Header_textBrowser")
        self.verticalLayout.addWidget(self.Header_textBrowser)
        self.Content_textBrowser = QtWidgets.QTextBrowser(parent=self.widget)
        self.Content_textBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.Content_textBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Content_textBrowser.setObjectName("Content_textBrowser")
        self.verticalLayout.addWidget(self.Content_textBrowser)
        self.verticalLayout.setStretch(1, 1)
        self.splitter.raise_()
        self.Article_listWidget.raise_()
        self.Header_textBrowser.raise_()
        self.Content_textBrowser.raise_()
        self.Post_pushButton.raise_()
        self.Delete_pushButton.raise_()

        self.retranslateUi(Forum)
        QtCore.QMetaObject.connectSlotsByName(Forum)

    def retranslateUi(self, Forum):
        _translate = QtCore.QCoreApplication.translate
        Forum.setWindowTitle(_translate("Forum", "Forum"))
        self.Post_pushButton.setText(_translate("Forum", "Post"))
        self.Delete_pushButton.setText(_translate("Forum", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forum = QtWidgets.QWidget()
    ui = Ui_Forum()
    ui.setupUi(Forum)
    Forum.show()
    sys.exit(app.exec())
