# Form implementation generated from reading ui file 'forum.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Forum(object):
    def setupUi(self, Forum):
        Forum.setObjectName("Forum")
        Forum.resize(1000, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Forum.sizePolicy().hasHeightForWidth())
        Forum.setSizePolicy(sizePolicy)
        Forum.setAutoFillBackground(False)
        self.Post_pushButton = QtWidgets.QPushButton(parent=Forum)
        self.Post_pushButton.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Post_pushButton.setFont(font)
        self.Post_pushButton.setObjectName("Post_pushButton")
        self.splitter = QtWidgets.QSplitter(parent=Forum)
        self.splitter.setGeometry(QtCore.QRect(10, 49, 981, 680))
        self.splitter.setMinimumSize(QtCore.QSize(100, 680))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Article_listWidget = QtWidgets.QListWidget(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Article_listWidget.sizePolicy().hasHeightForWidth())
        self.Article_listWidget.setSizePolicy(sizePolicy)
        self.Article_listWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.Article_listWidget.setObjectName("Article_listWidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.layoutWidget)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 472, 334))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Comment_textEdit = QtWidgets.QTextEdit(parent=self.layoutWidget)
        self.Comment_textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Comment_textEdit.setFont(font)
        self.Comment_textEdit.setObjectName("Comment_textEdit")
        self.horizontalLayout.addWidget(self.Comment_textEdit)
        self.Send_pushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.Send_pushButton.setFont(font)
        self.Send_pushButton.setObjectName("Send_pushButton")
        self.horizontalLayout.addWidget(self.Send_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter.raise_()
        self.Post_pushButton.raise_()

        self.retranslateUi(Forum)
        QtCore.QMetaObject.connectSlotsByName(Forum)

    def retranslateUi(self, Forum):
        _translate = QtCore.QCoreApplication.translate
        Forum.setWindowTitle(_translate("Forum", "Forum"))
        self.Post_pushButton.setText(_translate("Forum", "Post"))
        self.Comment_textEdit.setPlaceholderText(_translate("Forum", "Write something..."))
        self.Send_pushButton.setText(_translate("Forum", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forum = QtWidgets.QWidget()
    ui = Ui_Forum()
    ui.setupUi(Forum)
    Forum.show()
    sys.exit(app.exec())
