# Form implementation generated from reading ui file 'post.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Post(object):
    def setupUi(self, Post):
        Post.setObjectName("Post")
        Post.resize(800, 540)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        Post.setPalette(palette)
        self.Title_lineEdit = QtWidgets.QLineEdit(parent=Post)
        self.Title_lineEdit.setGeometry(QtCore.QRect(20, 30, 760, 30))
        self.Title_lineEdit.setObjectName("Title_lineEdit")
        self.Content_textEdit = QtWidgets.QTextEdit(parent=Post)
        self.Content_textEdit.setGeometry(QtCore.QRect(20, 90, 760, 400))
        self.Content_textEdit.setObjectName("Content_textEdit")
        self.Content_label = QtWidgets.QLabel(parent=Post)
        self.Content_label.setGeometry(QtCore.QRect(30, 70, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.Content_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Content_label.setFont(font)
        self.Content_label.setObjectName("Content_label")
        self.Title_label = QtWidgets.QLabel(parent=Post)
        self.Title_label.setGeometry(QtCore.QRect(30, 10, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.Title_label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Title_label.setFont(font)
        self.Title_label.setObjectName("Title_label")
        self.Post_pushButton = QtWidgets.QPushButton(parent=Post)
        self.Post_pushButton.setGeometry(QtCore.QRect(684, 500, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Post_pushButton.setFont(font)
        self.Post_pushButton.setObjectName("Post_pushButton")
        self.Cancel_pushButton = QtWidgets.QPushButton(parent=Post)
        self.Cancel_pushButton.setGeometry(QtCore.QRect(570, 500, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Cancel_pushButton.setFont(font)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")

        self.retranslateUi(Post)
        QtCore.QMetaObject.connectSlotsByName(Post)

    def retranslateUi(self, Post):
        _translate = QtCore.QCoreApplication.translate
        Post.setWindowTitle(_translate("Post", "Post"))
        self.Content_label.setText(_translate("Post", "Content"))
        self.Title_label.setText(_translate("Post", "Title"))
        self.Post_pushButton.setText(_translate("Post", "Post"))
        self.Cancel_pushButton.setText(_translate("Post", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Post = QtWidgets.QWidget()
    ui = Ui_Post()
    ui.setupUi(Post)
    Post.show()
    sys.exit(app.exec())
