# Project: Quadratic_Equation_Verifier_D1171708
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = complex_D1171708.o quadratic_equation_verifier_D1171708.o
LINKOBJ  = complex_D1171708.o quadratic_equation_verifier_D1171708.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = 
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Quadratic_Equation_Verifier_D1171708.exe
CXXFLAGS = $(CXXINCS) -std=c11
CFLAGS   = $(INCS) -std=c11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

complex_D1171708.o: complex_D1171708.c
	$(CC) -c complex_D1171708.c -o complex_D1171708.o $(CFLAGS)

quadratic_equation_verifier_D1171708.o: quadratic_equation_verifier_D1171708.c
	$(CC) -c quadratic_equation_verifier_D1171708.c -o quadratic_equation_verifier_D1171708.o $(CFLAGS)
