@startuml
'https://plantuml.com/sequence-diagram
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow false
skinparam style strictuml
hide unlinked
!pragma teoz true
autonumber

database "Database" as sql order 4
participant "Server" as server order 3
participant "RPC" as rpc order 2
participant "Client" as client order 1
participant "GUI" as gui order 0

hnote over gui: show Home Window
hnote over gui: show chatroom
hnote over gui: select file path to send file
gui -> client: send file path
gui -> client: request send file
hnote over client: convert file to Binary data
client -> rpc: request receive file
rpc -> server: send Binary data
hnote over server: parse filename and data
server -> sql: insert file
==Send File Done==

@enduml
