# Form implementation generated from reading ui file 'producer.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.label_Number = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Number.sizePolicy().hasHeightForWidth())
        self.label_Number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_Number.setFont(font)
        self.label_Number.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_Number.setObjectName("label_Number")
        self.verticalLayout_5.addWidget(self.label_Number)
        self.lineEdit_Number = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Number.sizePolicy().hasHeightForWidth())
        self.lineEdit_Number.setSizePolicy(sizePolicy)
        self.lineEdit_Number.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Number.setObjectName("lineEdit_Number")
        self.verticalLayout_5.addWidget(self.lineEdit_Number)
        self.btn_Produce = QtWidgets.QPushButton(parent=Form)
        self.btn_Produce.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Produce.setFlat(False)
        self.btn_Produce.setObjectName("btn_Produce")
        self.verticalLayout_5.addWidget(self.btn_Produce)
        self.btn_Close = QtWidgets.QPushButton(parent=Form)
        self.btn_Close.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_Close.setFlat(False)
        self.btn_Close.setObjectName("btn_Close")
        self.verticalLayout_5.addWidget(self.btn_Close)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 9)
        self.horizontalLayout.setStretch(2, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Producer"))
        self.label_Number.setText(_translate("Form", "Number"))
        self.lineEdit_Number.setPlaceholderText(_translate("Form", "10"))
        self.btn_Produce.setText(_translate("Form", "Produce"))
        self.btn_Close.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
