x = 0:pi/20:5*pi;
y1 = exp(-0.2*x) .* sin(2*x);
y2 = exp(-0.1*x) .* cos(4*x);
figure;
plot(x, y1, 'r-', 'LineWidth', 1.5);
hold on;
plot(x, y2, 'b-.', 'LineWidth', 1.5);
xlabel('x-axis');
ylabel('y-axis');
title('Question 1');
legend('function1', 'function2');
h = gcf; 
lines = findobj(h, 'Type', 'Line');
set(lines(1), 'Color', 'blue', 'LineStyle', '--'); 
set(lines(2), 'Color', 'magenta', 'LineStyle', '--');