@startuml
'https://plantuml.com/sequence-diagram
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow false
skinparam style strictuml
hide unlinked
!pragma teoz true
autonumber

database "Database" as sql order 4
participant "Server" as server order 3
participant "RPC" as rpc order 2
participant "Client" as client order 1
participant "GUI" as gui order 0

alt Login Button clicked
    hnote over gui: switch to Login Window
end
hnote over gui: Register Button clicked
gui -> client: send username, password,\nand confirm_password
client -> rpc: request register verify
rpc -> server: request user information
server -> sql: request user information
server <- sql: return user information
rpc <- server: return user information
hnote over rpc: verify user information
client <- rpc: return verification
alt register successfully
    gui <- client: verify successfully
    &rpc -> server: register user information
    server -> sql: insert user information
    hnote over gui: show Login Window
else register failed
    gui <- client: verify failed
    hnote over gui: clear line edit
end
==Register Done==

@enduml
