/*
  A classical cipher is substitution cipher that letters are one-to-one systematically
  mapped to other letters. The mapping is called the code book of a substitution cipher.
  A code bood is given in the program as array "code_book". Write a C program to perform 
  the following steps:
    1. Input an English text;
	2. Remove white spaces and punctuation symbols;
	3. Convert all lower case letters to upper case letters;
	4. Encode the text using the above code book;
	5. Output the original text and the encoded text;
	6. GGenerate the decode book, which is an inverse function of the code book;
	7. Decode the encoded text and output the decoding result.
  Assume the maximum characters in the input length is 10,000.
  Use MDOS pipeline commands to input (<) and output (>) the orginal text and the encoded text.
*/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

int main(void) {    
  // Code book. 
  //                     A    B    C    D    E    F    G    H    I    J    K    L    M    
  char code_book[26] = {'N', 'E', 'I', 'Q', 'O', 'Y', 'A', 'R', 'D', 'C', 'S', 'H', 'X',  
  //                     N    O    P    Q    R    S    T    U    V    W    X    Y    Z   
                        'Z', 'B', 'P', 'J', 'T', 'K', 'U', 'F', 'L', 'V', 'G', 'W', 'M'};
  char decode_book[26]; // Decode book, generated by the program.
  char original_text[10001]; // The original input text.
  char encoded_text[10001]; // Encoded text.
  char decoded_text[10001]; // Decoded text.
  int i, j; // Loop variable. 
  
  i = 0; // Inintial loop varible i to 0.
  do {
  	original_text[i++] = getchar(); // Input a character from the console.
  } while (!feof(stdin)); // Stop until the end of file.
  original_text[i] = '\0'; // Insert end-of-string.

  printf(">>>> The input original text:\n\n%s\n\n", original_text); // Output the original text.
  // Output a separated line.
  printf("-------------------------------------------------------------------------\n"); 
  
  j = 0; // Initial the index of the encoded text to 0.
  for (i=0; i<strlen(original_text); i++) // Scan the entire original text.
    // Convert English to upper case and encode a character.
    if (isalpha(original_text[i])) encoded_text[j++] = code_book[toupper(original_text[i]) - 'A'];
  encoded_text[j] = '\0'; // Insert end-of-string.

  printf(">>>> The encoded text:\n\n%s\n\n", encoded_text); // Output the encoded text.
  // Output a separated line.
  printf("-------------------------------------------------------------------------\n"); 
    
  for (i=0; i<26; i++) decode_book[code_book[i]-'A'] = i + 'A'; // Create the decode book.
  
  for (i=0; i<strlen(encoded_text); i++) // Scan the entire encoded text.
    decoded_text[i] = decode_book[encoded_text[i] - 'A']; // Decode a character.
  decoded_text[i] = '\0'; // Insert end-of-string.

  printf(">>>> The decoded text:\n\n%s\n\n", decoded_text); // Output the encoded text.
  // Output a separated line.
  printf("-------------------------------------------------------------------------\n"); 
    
  return 0;
}
