# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        self.Username_lineEdit = QtWidgets.QLineEdit(parent=Login)
        self.Username_lineEdit.setGeometry(QtCore.QRect(50, 60, 311, 31))
        self.Username_lineEdit.setObjectName("Username_lineEdit")
        self.Username_label = QtWidgets.QLabel(parent=Login)
        self.Username_label.setGeometry(QtCore.QRect(50, 40, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Username_label.setFont(font)
        self.Username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Username_label.setObjectName("Username_label")
        self.Password_lineEdit = QtWidgets.QLineEdit(parent=Login)
        self.Password_lineEdit.setGeometry(QtCore.QRect(50, 120, 311, 31))
        self.Password_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.Password_label = QtWidgets.QLabel(parent=Login)
        self.Password_label.setGeometry(QtCore.QRect(50, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Password_label.setFont(font)
        self.Password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Password_label.setObjectName("Password_label")
        self.Login_button = QtWidgets.QPushButton(parent=Login)
        self.Login_button.setGeometry(QtCore.QRect(50, 180, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Login_button.setFont(font)
        self.Login_button.setObjectName("Login_button")
        self.New_to_here_label = QtWidgets.QLabel(parent=Login)
        self.New_to_here_label.setGeometry(QtCore.QRect(80, 230, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.New_to_here_label.setFont(font)
        self.New_to_here_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.New_to_here_label.setObjectName("New_to_here_label")
        self.Register_label = QtWidgets.QLabel(parent=Login)
        self.Register_label.setGeometry(QtCore.QRect(200, 230, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Register_label.setFont(font)
        self.Register_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Register_label.setObjectName("Register_label")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.Username_label.setText(_translate("Login", "Username"))
        self.Password_label.setText(_translate("Login", "Password"))
        self.Login_button.setText(_translate("Login", "Login"))
        self.New_to_here_label.setText(_translate("Login", "New to Here?"))
        self.Register_label.setText(_translate("Login", "<a href=\"register\">Create an account</a>\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
